package com.agrialert.data_manager;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

/**
 * Represents a geographical field entity within the data management system.
 * <p>
 * This class is a Room entity that stores information about a specific field, including its
 * physical location (address, latitude, and longitude), the type of crop currently planted,
 * and its association with a specific {@link FieldsGroup}.
 * </p>
 *
 * <p>
 * It maintains a foreign key relationship with the {@code FieldsGroup} table, where
 * deleting a group will reset the associated fields to a default group.
 * </p>
 */
@Entity(foreignKeys = @ForeignKey(entity = FieldsGroup.class,
        parentColumns = "name",
        childColumns = "groupName",
        onDelete = ForeignKey.SET_DEFAULT))
public class Field {

    /**
     * The unique identifier for the field, automatically generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    private int id;

    /**
     * The physical address of the field.
     */
    @ColumnInfo(name = "adress")
    private String address;

    /**
     * The latitude coordinate of the field's geographic location.
     */
    @ColumnInfo(name = "latitude")
    private Double latitude;

    /**
     * The geographic longitude coordinate of the field.
     */
    @ColumnInfo(name = "longitude")
    private Double longitude;

    /**
     * The name of the group to which this field belongs. This acts as a foreign key
     * linking to the {@link FieldsGroup} entity and defaults to "default" if the
     * referenced group is deleted.
     * Note that the default group will always exists at time of creation of the db an cannot be deleted.
     */
    @ColumnInfo(name = "groupName", index = true, defaultValue = "Default")
    private String groupName;

    /**
     * The type of crop currently planted or associated with this field.
     * NONE for fields without crops.
     */
    @ColumnInfo(name = "crop_type")
    private CropType cropType;


    /**
     * Constructs a new Field with the specified address, coordinates, group, and crop type.
     * A group with name groupName should already exists at time of creation of the object.
     *
     * @param address   the physical address of the field
     * @param latitude  the geographical latitude coordinate of the field
     * @param longitude the geographical longitude coordinate of the field
     * @param groupName the name of the group this field belongs to
     * @param cropType  the type of crop planted in the field
     */
    public Field(String address, Double latitude, Double longitude, String groupName, CropType cropType) {
        this.address = address;
        this.latitude = latitude;
        this.longitude = longitude;
        this.groupName = groupName;
        this.cropType = cropType;
    }

    /**
     * Gets the unique identifier of the field.
     *
     * @return the field ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the field.
     * This method should not be used in production code.
     *
     * @param id the field ID to set
     */
    protected void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the address of the field.
     *
     * @return the field address
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the address of the field.
     *
     * @param address the address to set
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Gets the latitude coordinate of the field.
     *
     * @return the latitude as a Double
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * Sets the latitude of the field's location.
     *
     * @param latitude the latitude to set
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * Gets the longitude coordinate of the field.
     *
     * @return the longitude of the field
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * Sets the longitude coordinate of the field.
     *
     * @param longitude the longitude coordinate to set
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * Returns the name of the group to which this field belongs.
     *
     * @return the name of the associated group
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * Sets the name of the group to which this field belongs.
     * The new groupName must already exists.
     *
     * @param groupName the name of the group to associate with this field
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * Gets the type of crop currently planted in the field.
     *
     * @return the crop type
     */
    public CropType getCropType() {
        return cropType;
    }

    /**
     * Sets the type of crop cultivated in this field.
     * Use type NONE for fields without crops.
     *
     * @param cropType the type of crop to be associated with the field
     */
    public void setCropType(CropType cropType) {
        this.cropType = cropType;
    }


    /**
     * Returns a string representation of the Field object.
     *
     * @return a string describing the field's properties
     */
    @Override
    public String toString() {
        return "Field{" +
                "id=" + id +
                ", address='" + address + '\'' +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", groupName='" + groupName + '\'' +
                ", cropType=" + cropType +
                '}';
    }
}
